build: ksh93: put SHOPT_* option probes in iffe test (re: abbd9ffa)
Having the code to read/probe most SHOPT_* options in the Mamfile
is not actually the easiest way to maintain it. And one option
probe (SHOPT_GLOBCASEDET) can't be there because it is a C test,
so it's in the features/options iffe script. But iffe scripts can
run shell scripts as well as Mamfiles can, so this commit just puts
everything there, in one place. Very little code change was needed.

src/cmd/INIT/iffe.sh:
- Make file descriptor 9 available in the run{ command for log
  output, same as with anything run via execute().

src/cmd/ksh93/Mamfile,
src/cmd/ksh93/features/options:
- Move SHOPT_* options probe code to the iffe test, executing it
  with the run{ command. Write log output to file descriptor 9.

src/cmd/ksh93/tests/shtests:
- Grep FEATURE/options instead of shopt.h for compile-time options.

src/cmd/ksh93/*/*.c:
- Drop shopt.h and include FEATURE/options directly instead.

diff --git a/src/cmd/ksh93/tests/shtests b/src/cmd/ksh93/tests/shtests
--- a/src/cmd/ksh93/tests/shtests
+++ b/src/cmd/ksh93/tests/shtests
@@ -28,7 +28,7 @@ valgrindflags='--xml=yes --log-file=/dev/null --track-origins=yes --read-var-inf
 
 USAGE=$'
 [-s8?
-@(#)$Id: shtests (ksh 93u+m) 2026-03-19 $
+@(#)$Id: shtests (ksh 93u+m) 2026-03-30 $
 ]
 [-author?David Korn <dgk@research.att.com>]
 [-author?Glenn Fowler <gsf@research.att.com>]
@@ -327,24 +327,14 @@ fi
 export HOME=$tmp
 
 # make the SHOPT_* macros available to the tests as environment variables
-command unset "${!SHOPT_@}" 2>/dev/null
-SHOPT()
-{
-	[[ $1 == *=* ]] && eval "export SHOPT_${ printf %q "${1%%=*}"; }=${ printf %q "${1#*=}"; }"
-}
-. "${SHOPTFILE:-../SHOPT.sh}"
-unset -f SHOPT
-# override with probed values from shopt.h:
-# change '#define SHOPT_foo = bar' to 'export SHOPT_foo=bar' and evaluate
-if	[[ -f $INSTALLROOT/src/cmd/ksh93/shopt.h ]] &&
-	i=$(sed -n $'/^#[ \t]*define[ \t][ \t]*SHOPT_/ {
-				s/.*define[ \t][ \t]*//
-				s/[ \t][ \t]*/=/
-				s/^/export /
-				p
-			}' "$INSTALLROOT"/src/cmd/ksh93/shopt.h)
-then	eval "$i" || exit
-else	echo "$0: cannot grep shopt.h" >&2
+# find $'#   define SHOPT_foo\tbar', change to '[[ -v SHOPT_foo ]] || export SHOPT_foo=bar' and evaluate
+t=$INSTALLROOT/src/cmd/ksh93/FEATURE/options
+if	[[ -f $t ]] &&
+	i=$(sed -n 's/^#   define \(SHOPT_[A-Za-z0-9_]*\)	\(.*\)/[[ -v \1 ]] || export \1=\2/p' "$t") &&
+	[[ -n $i ]] &&
+	eval "$i"
+then	: ok
+else	echo "$0: failed to read FEATURE/options" >&2
 	exit 1
 fi
 
